### ISSUE TITLE
Break down your project by creating issues which makes the whole project.

### ISSUE THREAD

**Issue by naz-hage** [ahmdhjj92/cv-builder#6]
create a single PR for each issue and merge only after it is implemented, reviewed, tested.    Once PR is merge, close the issue
As an example:    Implement the register action.  In this issue, you design what is required, implement and start a PR.

It's up to you to create the issues but I recommend to break down the project into smaller issues.

This issue is just a sample.  you can ad comments to enhance it and close it at any time.

**Comment by ahmdhjj92** [comment]
Noted.
